exclude: (^.idea/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
        types: [ python ]
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        language: system
        types: [ python ]
        entry: autoflake
        require_serial: true
        args: [ '--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports']
      - id: flake8
        name: flake8
        language: system
        types: [python]
        entry: flake8
        require_serial: true
      - id: black
        name: black
        language: system
        types: [python]
        require_serial: true
        entry: black
      - id: pyre-check
        name: pyre-check
        language: system
        types: [ python ]
        entry: pyre --source-directory . check
        pass_filenames: false
        additional_dependencies: []