version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: spark.Dockerfile
      context: .
    image: sparkautomapper_dev
    volumes:
      - ./:/sam/
      - ~/.local/share/virtualenvs:/root/.local/share/virtualenvs:rw
    container_name: sam_dev
    working_dir: /sam
