version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: spark.Dockerfile
      context: .
    image: sparkautomapper_dev
    volumes:
      - ./:/sam/
    container_name: sam_dev
    working_dir: /sam
