#!/bin/bash

GIT_PROJECT_ROOT=$(git rev-parse --show-toplevel)
cd "$($GIT_PROJECT_ROOT "$0")"
# NOTE: pre-commit.Dockerfile stays on Docker Hub's python:3.12-slim, so no ECR
# login is needed here. (spark.Dockerfile does need one -- see `make ecr-login`.)
docker build -f ./pre-commit.Dockerfile -t pre-commit-sam . && \
docker run --rm --name pre-commit-sam-run \
  --user "$(id -u):$(id -g)" -e HOME=/tmp \
  -v $(pwd)/:/sourcecode pre-commit-sam
